# Importamos numpy e carregamos um arquivo para ser usado no teste da função

In [4]:
import numpy as np
arquivo=np.loadtxt("dados\\brazil-TAVG-Trend.txt", comments='%')

# Definimos as variáveis "anos" e "meses" e definimos a função "anos_dec"

In [29]:
anos=arquivo[:,0]
meses=arquivo[:,1]
def anos_dec(anos, meses):
    assert type(anos)==np.ndarray, "Tipo de variável errada"
    assert type(meses)==np.ndarray, "Tipo de variável errada"
    return anos+(meses-1)/12

# Testamos a função com os dados do arquivo carregado

In [30]:
anos_dec(anos, meses)

array([ 1832.        ,  1832.08333333,  1832.16666667, ...,  2013.5       ,
        2013.58333333,  2013.66666667])

In [32]:
temp=arquivo[:,2]
def temp_anodec_anomanual_incanomanual_ano10_incano10(temp):
    assert type(temp)==np.ndarray, "Tipo de variável errada"
    anomanual=arquivo[:,4]
    incanomanual=arquivo[:,5]
    ano10=arquivo[:,8]
    incano10=arquivo[:,9]
    return (anos_dec(anos, meses),anomanual, incanomanual, ano10, incano10)

In [33]:
temp_anodec_anomanual_incanomanual_ano10_incano10(temp)

(array([ 1832.        ,  1832.08333333,  1832.16666667, ...,  2013.5       ,
         2013.58333333,  2013.66666667]),
 array([ nan,  nan,  nan, ...,  nan,  nan,  nan]),
 array([ nan,  nan,  nan, ...,  nan,  nan,  nan]),
 array([ nan,  nan,  nan, ...,  nan,  nan,  nan]),
 array([ nan,  nan,  nan, ...,  nan,  nan,  nan]))